engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
    phpmd:
      enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
  - tests/
