language: php
dist: trusty

php:
  - '5.6'
  - '7.0'
  - hhvm

install:
  - pip install --user termcolor
  - export PATH=$PATH:$HOME/.local/bin

script: make && python ./tools/testsuite/run-tests.py --dir tests --exe "php ./bin/quack %s"
