language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install: pip install hy

script:
  - make test module=lexer
  - make test module=parser

addons:
  apt:
    packages:
      - python-pip
