language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - pip install --user hy
  - pip install termcolor
  - export PATH=$PATH:$HOME/.local/bin

script:
  - make test module=lexer
  - make test module=parser
  - hy ./tools/testsuite/run-tests.hy --dir tests --exe "./tools/testsuite/file_to_stdout %s"
