language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - pip install --user hy
  - pip install --user termcolor
  - export PATH=$PATH:$HOME/.local/bin

script:
  - make test module=lexer
  - make test module=parser
  - hy ./tools/testsuite/run-tests.hy --dir tests --exe "php ./src/Quack.php %s"
